# specific path build
trigger:
  - SAE-Registred
    

jobs:
  - job: Build_SAE_Opcc
    pool: 'BUILD-SERVER'
#      name: Default
#      demands:
    variables:
      java_version: '17'
      jdkVersion: '17'
      SPRING_OUTPUT_ANSI_ENABLED: NEVER
      SPRING_JPA_SHOW_SQL: false
      artifactName: ''
  

    steps:
      - script: | 
          echo "Version du JDK :" 
          java -version : 
        displayName: 'Afficher la version du JDK'
      - script: | 
          echo "Version du MVN :" 
          mvn --version : 
        displayName: 'Afficher la version du MVN'


      #----------------------------------------------------------------------
      # ADD Permission
      #----------------------------------------------------------------------
      - script: chmod 777 $(system.defaultworkingdirectory)/mvnw
        displayName: 'ADD Permission'


      #----------------------------------------------------------------------
      # Apply Spotless
      #----------------------------------------------------------------------
      - script: mvn spotless:apply
        displayName: 'Apply Spotless'


      #----------------------------------------------------------------------
      # Test Packaging
      #----------------------------------------------------------------------
      - script: ./mvnw -DskipTests clean verify
        displayName: 'TESTS: packaging'

      - script: |
          docker build -f ./dockerfile -t 192.168.30.15:1200/sae-opcc:$(Build.BuildNumber) .
        displayName: 'Build Docker Image from Dockerfile' 

      
      #----------------------------------------------------------------------
      # Build Docker Image
      #----------------------------------------------------------------------
      - script: ./mvnw package -Pprod -DskipTests jib:dockerBuild
        displayName: 'Build Docker Image'
      - script: |
          docker tag sae-opcc:latest sae-opcc:$(Build.BuildNumber)
          cd /home/administrateur/myagent1/_work/8/s
          echo "TAG6="$(Build.BuildNumber) >> .env
        displayName: 'Docker TAG Image'

#----------------------------------------------------------------------
# Connect to Nexus
#----------------------------------------------------------------------
      - script: docker login -u admin -p It@*2021 http://192.168.30.15:1200
        displayName: 'Connect to Nexus'

#----------------------------------------------------------------------
# Push image to nexus
#----------------------------------------------------------------------
      - script: docker tag sae-opcc:latest 192.168.30.15:1200/sae-opcc:$(Build.BuildNumber)
        displayName: 'docker tag image to nexus'
      - script: docker push 192.168.30.15:1200/sae-opcc:$(Build.BuildNumber)
        displayName: 'docker push image to nexus'

#----------------------------------------------------------------------
# Connect to Kubernetes Server.
#----------------------------------------------------------------------
      - task: SSH@0
        inputs:
          sshEndpoint: 'Kub-ssh'
          runOptions: 'inline'
          inline: |
            export KUBECONFIG=/etc/kubernetes/admin.conf
            kubectl set image deployment/sae-opcc -n fa-dev sae-opcc-app=192.168.30.15:1200/sae-opcc:$(Build.BuildNumber)

        