package com.fininfo.saeopcc.shared.domains.enumeration;

public enum BondNature {
  CERTIFICATE_OF_DEPOSIT,
  ISSUED_BOND_DEBT,
  DEBT_SECURITIES_ISSUED,
  SUBORDINATED_TERM_SECURITIES,
  SUBORDINATED_FIXED_TERM_SECURITIES_ISSUED_TO_CREDIT_INSTITUTIONS_AND_SIMILAR_ENTITIES,
  PERPERTUAL_SUBORDINATED_SECURITIES,
  PERPERTUAL_SUBORDINATED_SECURITIES_ISSUED_TO_CREDIT_INSTITUTIONS_AND_SIMILAR_ENTITIES,
}
