package com.fininfo.saeopcc.shared.domains.enumeration;

/** The OperationType enumeration. */
public enum OperationType {
  OVERTHECOUNTEROPERATION,
  STOCKEXCHANGEOPERATION,
  ASSETSFUNDOPERATION,
  LIABILITIESFUNDOPERATION,
  LENDOPERATION,
  BORROWOPERATION,
  REPOOPERATION,
  REVERSEREPOOPERATION,
  GUARANTEEOPERATION,
  PURECASHOPERATION,
  TRANSFERTOPERATION,
  PAYMENTOPERATION,
  CHECKOPERATION
}
