#Feature: IRL Operations
#
  ###########################################################
  #@Test
  #Scenario: Save BUY IRL Entity
    #When I save an IRL entity with operationType BUY and details:
      #"""
      #{
        #"id": null,
        #"reference": null,
        #"clientReference": "6432",
        #"clientDescription": "SHAREH1",
        #"counterpartReference": "76542",
        #"counterpartDescription": "IFH1",
        #"shareholderReference": "6432",
        #"shareholderDescription": "SHAREH1",
        #"isin": "MA90002",
        #"operationType": "BUY",
        #"transDirection": 1,
        #"assetType": "EQUITY",
        #"assetDescription": "JHZZT",
        #"assetId": 41,
        #"assetReference": "7777",
        #"quantity": 12,
        #"quantityType": "UNIT",
        #"shareholderId": 11,
        #"counterpartId": 11,
        #"beneficiaryId": 0,
        #"csdId": 0,
        #"csdReference": "",
        #"csdDescription": "",
        #"clientSecurityAccount": "236721419000264320000033333010301",
        #"clientCashAccount": "",
        #"beneficiarySecurityAccount": "",
        #"beneficiaryCashAccount": "",
        #"currencyCashAccount": 0,
        #"nostroSecurityAccount": 0,
        #"nostroCashAccount": 0,
        #"operationDate": "2024-01-28",
        #"valueDate": null,
        #"settlementDate": "2024-01-29",
        #"grossAmount": 1200,
        #"vatAmount": 0,
        #"whtAmount": 0,
        #"netAmount": 1200,
        #"cashAccountcurrencyId": 0,
        #"cashAccountcurrency": "",
        #"currency": "MAD",
        #"accuredInterest": 0,
        #"settlementPlace": "",
        #"reversed": false,
        #"clientProviderId": 0,
        #"clientProviderDescription": "",
        #"sens": "RECEIVE",
        #"maturityDate": null,
        #"status": "PREVALIDATED",
        #"rate": 0,
        #"transferred": true,
        #"price": 100,
        #"active": true,
        #"placeOfSettlement": "MAROCLEAR",
        #"origin": "MANUAL"
      #}
      #"""
    #Then the IRL entity should be saved successfully
    #And the IRLs should be marked as PREVALIDATED
#
  ###########################################################
  #@Test
  #Scenario: Save SELL IRL Entity
    #When I save an IRL entity with operationType SELL and details:
      #"""
      #{
        #"id": null,
        #"reference": null,
        #"clientReference": "6432",
        #"clientDescription": "SHAREH1",
        #"counterpartReference": "76542",
        #"counterpartDescription": "IFH1",
        #"shareholderReference": "6432",
        #"shareholderDescription": "SHAREH1",
        #"isin": "MA90002",
        #"operationType": "SELL",
        #"transDirection": 1,
        #"assetType": "EQUITY",
        #"assetDescription": "JHZZT",
        #"assetId": 41,
        #"assetReference": "7777",
        #"quantity": 12,
        #"quantityType": "UNIT",
        #"shareholderId": 11,
        #"counterpartId": 11,
        #"beneficiaryId": 0,
        #"csdId": 0,
        #"csdReference": "",
        #"csdDescription": "",
        #"clientSecurityAccount": "236721419000264320000033333010301",
        #"clientCashAccount": "",
        #"beneficiarySecurityAccount": "",
        #"beneficiaryCashAccount": "",
        #"currencyCashAccount": 0,
        #"nostroSecurityAccount": 0,
        #"nostroCashAccount": 0,
        #"operationDate": "2024-01-28",
        #"valueDate": null,
        #"settlementDate": "2024-01-29",
        #"grossAmount": 1200,
        #"vatAmount": 0,
        #"whtAmount": 0,
        #"netAmount": 1200,
        #"cashAccountcurrencyId": 0,
        #"cashAccountcurrency": "",
        #"currency": "MAD",
        #"accuredInterest": 0,
        #"settlementPlace": "",
        #"reversed": false,
        #"clientProviderId": 0,
        #"clientProviderDescription": "",
        #"sens": "RECEIVE",
        #"maturityDate": null,
        #"status": "PREVALIDATED",
        #"rate": 0,
        #"transferred": true,
        #"price": 100,
        #"active": true,
        #"placeOfSettlement": "MAROCLEAR",
        #"origin": "MANUAL"
      #}
      #"""
    #Then the IRL entity should be saved successfully
    #And the IRLs should be marked as PREVALIDATED
#
  ###########################################################
  #@Test
  #Scenario: Save BLOCK IRL Entity
    #When I save an IRL entity with operationType BLOCK and details:
      #"""
      #{
        #"id": null,
        #"reference": null,
        #"clientReference": "6432",
        #"clientDescription": "SHAREH1",
        #"counterpartReference": "76542",
        #"counterpartDescription": "IFH1",
        #"shareholderReference": "6432",
        #"shareholderDescription": "SHAREH1",
        #"isin": "MA90002",
        #"operationType": "BLOCK",
        #"transDirection": 1,
        #"assetType": "EQUITY",
        #"assetDescription": "JHZZT",
        #"assetId": 41,
        #"assetReference": "7777",
        #"quantity": 12,
        #"quantityType": "UNIT",
        #"shareholderId": 11,
        #"counterpartId": 11,
        #"beneficiaryId": 0,
        #"csdId": 0,
        #"csdReference": "",
        #"csdDescription": "",
        #"clientSecurityAccount": "236721419000264320000033333010301",
        #"clientCashAccount": "",
        #"beneficiarySecurityAccount": "",
        #"beneficiaryCashAccount": "",
        #"currencyCashAccount": 0,
        #"nostroSecurityAccount": 0,
        #"nostroCashAccount": 0,
        #"operationDate": "2024-01-28",
        #"valueDate": null,
        #"settlementDate": "2024-01-29",
        #"grossAmount": 1200,
        #"vatAmount": 0,
        #"whtAmount": 0,
        #"netAmount": 1200,
        #"cashAccountcurrencyId": 0,
        #"cashAccountcurrency": "",
        #"currency": "MAD",
        #"accuredInterest": 0,
        #"settlementPlace": "",
        #"reversed": false,
        #"clientProviderId": 0,
        #"clientProviderDescription": "",
        #"sens": "RECEIVE",
        #"maturityDate": null,
        #"status": "PREVALIDATED",
        #"rate": 0,
        #"transferred": true,
        #"price": 100,
        #"active": true,
        #"placeOfSettlement": "MAROCLEAR",
        #"origin": "MANUAL"
      #}
      #"""
    #Then the IRL entity should be saved successfully
    #And the IRLs should be marked as PREVALIDATED
#
  ###########################################################
  #@Test
  #Scenario: Save UNBLOCK IRL Entity
    #When I save an IRL entity with operationType UNBLOCK and details:
      #"""
      #{
        #"id": null,
        #"reference": null,
        #"clientReference": "6432",
        #"clientDescription": "SHAREH1",
        #"counterpartReference": "76542",
        #"counterpartDescription": "IFH1",
        #"shareholderReference": "6432",
        #"shareholderDescription": "SHAREH1",
        #"isin": "MA90002",
        #"operationType": "UNBLOCK",
        #"transDirection": 1,
        #"assetType": "EQUITY",
        #"assetDescription": "JHZZT",
        #"assetId": 41,
        #"assetReference": "7777",
        #"quantity": 12,
        #"quantityType": "UNIT",
        #"shareholderId": 11,
        #"counterpartId": 11,
        #"beneficiaryId": 0,
        #"csdId": 0,
        #"csdReference": "",
        #"csdDescription": "",
        #"clientSecurityAccount": "236721419000264320000033333010301",
        #"clientCashAccount": "",
        #"beneficiarySecurityAccount": "",
        #"beneficiaryCashAccount": "",
        #"currencyCashAccount": 0,
        #"nostroSecurityAccount": 0,
        #"nostroCashAccount": 0,
        #"operationDate": "2024-01-28",
        #"valueDate": null,
        #"settlementDate": "2024-01-29",
        #"grossAmount": 1200,
        #"vatAmount": 0,
        #"whtAmount": 0,
        #"netAmount": 1200,
        #"cashAccountcurrencyId": 0,
        #"cashAccountcurrency": "",
        #"currency": "MAD",
        #"accuredInterest": 0,
        #"settlementPlace": "",
        #"reversed": false,
        #"clientProviderId": 0,
        #"clientProviderDescription": "",
        #"sens": "RECEIVE",
        #"maturityDate": null,
        #"status": "PREVALIDATED",
        #"rate": 0,
        #"transferred": true,
        #"price": 100,
        #"active": true,
        #"placeOfSettlement": "MAROCLEAR",
        #"origin": "MANUAL"
      #}
      #"""
    #Then the IRL entity should be saved successfully
    #And the IRLs should be marked as PREVALIDATED
#
  ###########################################################
  #@Test
  #Scenario: Save SUBSCRIPTION IRL Entity
    #When I save an IRL entity with operationType SUBSCRIPTION and details:
      #"""
      #{
        #"id": null,
        #"reference": null,
        #"clientReference": "6432",
        #"clientDescription": "SHAREH1",
        #"counterpartReference": "76542",
        #"counterpartDescription": "IFH1",
        #"shareholderReference": "6432",
        #"shareholderDescription": "SHAREH1",
        #"isin": "MA90002",
        #"operationType": "SUBSCRIPTION",
        #"transDirection": 1,
        #"assetType": "EQUITY",
        #"assetDescription": "JHZZT",
        #"assetId": 41,
        #"assetReference": "7777",
        #"quantity": 12,
        #"quantityType": "UNIT",
        #"shareholderId": 11,
        #"counterpartId": 11,
        #"beneficiaryId": 0,
        #"csdId": 0,
        #"csdReference": "",
        #"csdDescription": "",
        #"clientSecurityAccount": "236721419000264320000033333010301",
        #"clientCashAccount": "",
        #"beneficiarySecurityAccount": "",
        #"beneficiaryCashAccount": "",
        #"currencyCashAccount": 0,
        #"nostroSecurityAccount": 0,
        #"nostroCashAccount": 0,
        #"operationDate": "2024-01-28",
        #"valueDate": null,
        #"settlementDate": "2024-01-29",
        #"grossAmount": 1200,
        #"vatAmount": 0,
        #"whtAmount": 0,
        #"netAmount": 1200,
        #"cashAccountcurrencyId": 0,
        #"cashAccountcurrency": "",
        #"currency": "MAD",
        #"accuredInterest": 0,
        #"settlementPlace": "",
        #"reversed": false,
        #"clientProviderId": 0,
        #"clientProviderDescription": "",
        #"sens": "RECEIVE",
        #"maturityDate": null,
        #"status": "PREVALIDATED",
        #"rate": 0,
        #"transferred": true,
        #"price": 100,
        #"active": true,
        #"placeOfSettlement": "MAROCLEAR",
        #"origin": "MANUAL"
      #}
      #"""
    #Then the IRL entity should be saved successfully
    #And the IRLs should be marked as PREVALIDATED
#
  ###########################################################
  #@Test
  #Scenario: Save REDEMPTION IRL Entity
    #When I save an IRL entity with operationType REDEMPTION and details:
      #"""
      #{
        #"id": null,
        #"reference": null,
        #"clientReference": "6432",
        #"clientDescription": "SHAREH1",
        #"counterpartReference": "76542",
        #"counterpartDescription": "IFH1",
        #"shareholderReference": "6432",
        #"shareholderDescription": "SHAREH1",
        #"isin": "MA90002",
        #"operationType": "REDEMPTION",
        #"transDirection": 1,
        #"assetType": "EQUITY",
        #"assetDescription": "JHZZT",
        #"assetId": 41,
        #"assetReference": "7777",
        #"quantity": 12,
        #"quantityType": "UNIT",
        #"shareholderId": 11,
        #"counterpartId": 11,
        #"beneficiaryId": 0,
        #"csdId": 0,
        #"csdReference": "",
        #"csdDescription": "",
        #"clientSecurityAccount": "236721419000264320000033333010301",
        #"clientCashAccount": "",
        #"beneficiarySecurityAccount": "",
        #"beneficiaryCashAccount": "",
        #"currencyCashAccount": 0,
        #"nostroSecurityAccount": 0,
        #"nostroCashAccount": 0,
        #"operationDate": "2024-01-28",
        #"valueDate": null,
        #"settlementDate": "2024-01-29",
        #"grossAmount": 1200,
        #"vatAmount": 0,
        #"whtAmount": 0,
        #"netAmount": 1200,
        #"cashAccountcurrencyId": 0,
        #"cashAccountcurrency": "",
        #"currency": "MAD",
        #"accuredInterest": 0,
        #"settlementPlace": "",
        #"reversed": false,
        #"clientProviderId": 0,
        #"clientProviderDescription": "",
        #"sens": "RECEIVE",
        #"maturityDate": null,
        #"status": "PREVALIDATED",
        #"rate": 0,
        #"transferred": true,
        #"price": 100,
        #"active": true,
        #"placeOfSettlement": "MAROCLEAR",
        #"origin": "MANUAL"
      #}
      #"""
    #Then the IRL entity should be saved successfully
    #And the IRLs should be marked as PREVALIDATED
#
#
  ###########################################################
  #@Test
  #Scenario: Save CONVERSION_PUR_ADMIN IRL Entity
    #When I save an IRL entity with operationType CONVERSION_PUR_ADMIN and details:
      #"""
      #{
        #"id": null,
        #"reference": null,
        #"clientReference": "6432",
        #"clientDescription": "SHAREH1",
        #"counterpartReference": "76542",
        #"counterpartDescription": "IFH1",
        #"shareholderReference": "6432",
        #"shareholderDescription": "SHAREH1",
        #"isin": "MA90002",
        #"operationType": "CONVERSION_PUR_ADMIN",
        #"transDirection": 1,
        #"assetType": "EQUITY",
        #"assetDescription": "JHZZT",
        #"assetId": 41,
        #"assetReference": "7777",
        #"quantity": 12,
        #"quantityType": "UNIT",
        #"shareholderId": 11,
        #"counterpartId": 11,
        #"beneficiaryId": 0,
        #"csdId": 0,
        #"csdReference": "",
        #"csdDescription": "",
        #"clientSecurityAccount": "236721419000264320000033333010301",
        #"clientCashAccount": "",
        #"beneficiarySecurityAccount": "",
        #"beneficiaryCashAccount": "",
        #"currencyCashAccount": 0,
        #"nostroSecurityAccount": 0,
        #"nostroCashAccount": 0,
        #"operationDate": "2024-01-28",
        #"valueDate": null,
        #"settlementDate": "2024-01-29",
        #"grossAmount": 1200,
        #"vatAmount": 0,
        #"whtAmount": 0,
        #"netAmount": 1200,
        #"cashAccountcurrencyId": 0,
        #"cashAccountcurrency": "",
        #"currency": "MAD",
        #"accuredInterest": 0,
        #"settlementPlace": "",
        #"reversed": false,
        #"clientProviderId": 0,
        #"clientProviderDescription": "",
        #"sens": "RECEIVE",
        #"maturityDate": null,
        #"status": "PREVALIDATED",
        #"rate": 0,
        #"transferred": true,
        #"price": 100,
        #"active": true,
        #"placeOfSettlement": "MAROCLEAR",
        #"origin": "MANUAL"
      #}
      #"""
    #Then the IRL entity should be saved successfully
    #And the IRLs should be marked as PREVALIDATED
#
  ###########################################################
  #@Test
  #Scenario: Save CONVERSION_ADMIN_PUR IRL Entity
    #When I save an IRL entity with operationType CONVERSION_ADMIN_PUR and details:
      #"""
      #{
        #"id": null,
        #"reference": null,
        #"clientReference": "6432",
        #"clientDescription": "SHAREH1",
        #"counterpartReference": "76542",
        #"counterpartDescription": "IFH1",
        #"shareholderReference": "6432",
        #"shareholderDescription": "SHAREH1",
        #"isin": "MA90002",
        #"operationType": "CONVERSION_ADMIN_PUR",
        #"transDirection": 1,
        #"assetType": "EQUITY",
        #"assetDescription": "JHZZT",
        #"assetId": 41,
        #"assetReference": "7777",
        #"quantity": 12,
        #"quantityType": "UNIT",
        #"shareholderId": 11,
        #"counterpartId": 11,
        #"beneficiaryId": 0,
        #"csdId": 0,
        #"csdReference": "",
        #"csdDescription": "",
        #"clientSecurityAccount": "236721419000264320000033333010301",
        #"clientCashAccount": "",
        #"beneficiarySecurityAccount": "",
        #"beneficiaryCashAccount": "",
        #"currencyCashAccount": 0,
        #"nostroSecurityAccount": 0,
        #"nostroCashAccount": 0,
        #"operationDate": "2024-01-28",
        #"valueDate": null,
        #"settlementDate": "2024-01-29",
        #"grossAmount": 1200,
        #"vatAmount": 0,
        #"whtAmount": 0,
        #"netAmount": 1200,
        #"cashAccountcurrencyId": 0,
        #"cashAccountcurrency": "",
        #"currency": "MAD",
        #"accuredInterest": 0,
        #"settlementPlace": "",
        #"reversed": false,
        #"clientProviderId": 0,
        #"clientProviderDescription": "",
        #"sens": "RECEIVE",
        #"maturityDate": null,
        #"status": "PREVALIDATED",
        #"rate": 0,
        #"transferred": true,
        #"price": 100,
        #"active": true,
        #"placeOfSettlement": "MAROCLEAR",
        #"origin": "MANUAL"
      #}
      #"""
    #Then the IRL entity should be saved successfully
    #And the IRLs should be marked as PREVALIDATED
#
#
  ###########################################################
  #@Test
  #Scenario: Save PLEDGE IRL Entity
    #When I save an IRL entity with operationType PLEDGE and details:
      #"""
      #{
        #"id": null,
        #"reference": null,
        #"clientReference": "6432",
        #"clientDescription": "SHAREH1",
        #"counterpartReference": "76542",
        #"counterpartDescription": "IFH1",
        #"shareholderReference": "6432",
        #"shareholderDescription": "SHAREH1",
        #"isin": "MA90002",
        #"operationType": "PLEDGE",
        #"transDirection": 1,
        #"assetType": "EQUITY",
        #"assetDescription": "JHZZT",
        #"assetId": 41,
        #"assetReference": "7777",
        #"quantity": 12,
        #"quantityType": "UNIT",
        #"shareholderId": 11,
        #"counterpartId": 11,
        #"beneficiaryId": 0,
        #"csdId": 0,
        #"csdReference": "",
        #"csdDescription": "",
        #"clientSecurityAccount": "236721419000264320000033333010301",
        #"clientCashAccount": "",
        #"beneficiarySecurityAccount": "",
        #"beneficiaryCashAccount": "",
        #"currencyCashAccount": 0,
        #"nostroSecurityAccount": 0,
        #"nostroCashAccount": 0,
        #"operationDate": "2024-01-28",
        #"valueDate": null,
        #"settlementDate": "2024-01-29",
        #"grossAmount": 1200,
        #"vatAmount": 0,
        #"whtAmount": 0,
        #"netAmount": 1200,
        #"cashAccountcurrencyId": 0,
        #"cashAccountcurrency": "",
        #"currency": "MAD",
        #"accuredInterest": 0,
        #"settlementPlace": "",
        #"reversed": false,
        #"clientProviderId": 0,
        #"clientProviderDescription": "",
        #"sens": "RECEIVE",
        #"maturityDate": null,
        #"status": "PREVALIDATED",
        #"rate": 0,
        #"transferred": true,
        #"price": 100,
        #"active": true,
        #"placeOfSettlement": "MAROCLEAR",
        #"origin": "MANUAL"
      #}
      #"""
    #Then the IRL entity should be saved successfully
    #And the IRLs should be marked as PREVALIDATED
  #
  ###########################################################
  #@Test
  #Scenario: Save UNPLEDGE IRL Entity
    #When I save an IRL entity with operationType UNPLEDGE and details:
      #"""
      #{
        #"id": null,
        #"reference": null,
        #"clientReference": "6432",
        #"clientDescription": "SHAREH1",
        #"counterpartReference": "76542",
        #"counterpartDescription": "IFH1",
        #"shareholderReference": "6432",
        #"shareholderDescription": "SHAREH1",
        #"isin": "MA90002",
        #"operationType": "UNPLEDGE",
        #"transDirection": 1,
        #"assetType": "EQUITY",
        #"assetDescription": "JHZZT",
        #"assetId": 41,
        #"assetReference": "7777",
        #"quantity": 12,
        #"quantityType": "UNIT",
        #"shareholderId": 11,
        #"counterpartId": 11,
        #"beneficiaryId": 0,
        #"csdId": 0,
        #"csdReference": "",
        #"csdDescription": "",
        #"clientSecurityAccount": "236721419000264320000033333010301",
        #"clientCashAccount": "",
        #"beneficiarySecurityAccount": "",
        #"beneficiaryCashAccount": "",
        #"currencyCashAccount": 0,
        #"nostroSecurityAccount": 0,
        #"nostroCashAccount": 0,
        #"operationDate": "2024-01-28",
        #"valueDate": null,
        #"settlementDate": "2024-01-29",
        #"grossAmount": 1200,
        #"vatAmount": 0,
        #"whtAmount": 0,
        #"netAmount": 1200,
        #"cashAccountcurrencyId": 0,
        #"cashAccountcurrency": "",
        #"currency": "MAD",
        #"accuredInterest": 0,
        #"settlementPlace": "",
        #"reversed": false,
        #"clientProviderId": 0,
        #"clientProviderDescription": "",
        #"sens": "RECEIVE",
        #"maturityDate": null,
        #"status": "PREVALIDATED",
        #"rate": 0,
        #"transferred": true,
        #"price": 100,
        #"active": true,
        #"placeOfSettlement": "MAROCLEAR",
        #"origin": "MANUAL"
      #}
      #"""
    #Then the IRL entity should be saved successfully
    #And the IRLs should be marked as PREVALIDATED
#
  ###########################################################
  #@Test
  #Scenario: Save TRANSFER_IN IRL Entity
    #When I save an IRL entity with operationType TRANSFER_IN and details:
      #"""
      #{
        #"id": null,
        #"reference": null,
        #"clientReference": "6432",
        #"clientDescription": "SHAREH1",
        #"counterpartReference": "76542",
        #"counterpartDescription": "IFH1",
        #"shareholderReference": "6432",
        #"shareholderDescription": "SHAREH1",
        #"isin": "MA90002",
        #"operationType": "TRANSFER_IN",
        #"transDirection": 1,
        #"assetType": "EQUITY",
        #"assetDescription": "JHZZT",
        #"assetId": 41,
        #"assetReference": "7777",
        #"quantity": 12,
        #"quantityType": "UNIT",
        #"shareholderId": 11,
        #"counterpartId": 11,
        #"beneficiaryId": 0,
        #"csdId": 0,
        #"csdReference": "",
        #"csdDescription": "",
        #"clientSecurityAccount": "236721419000264320000033333010301",
        #"clientCashAccount": "",
        #"beneficiarySecurityAccount": "",
        #"beneficiaryCashAccount": "",
        #"currencyCashAccount": 0,
        #"nostroSecurityAccount": 0,
        #"nostroCashAccount": 0,
        #"operationDate": "2024-01-28",
        #"valueDate": null,
        #"settlementDate": "2024-01-29",
        #"grossAmount": 1200,
        #"vatAmount": 0,
        #"whtAmount": 0,
        #"netAmount": 1200,
        #"cashAccountcurrencyId": 0,
        #"cashAccountcurrency": "",
        #"currency": "MAD",
        #"accuredInterest": 0,
        #"settlementPlace": "",
        #"reversed": false,
        #"clientProviderId": 0,
        #"clientProviderDescription": "",
        #"sens": "RECEIVE",
        #"maturityDate": null,
        #"status": "PREVALIDATED",
        #"rate": 0,
        #"transferred": true,
        #"price": 100,
        #"active": true,
        #"placeOfSettlement": "MAROCLEAR",
        #"origin": "MANUAL"
      #}
      #"""
    #Then the IRL entity should be saved successfully
    #And the IRLs should be marked as PREVALIDATED
#
  ###########################################################
  #@Test
  #Scenario: Save TRANSFER_OUT IRL Entity
    #When I save an IRL entity with operationType TRANSFER_OUT and details:
      #"""
      #{
        #"id": null,
        #"reference": null,
        #"clientReference": "6432",
        #"clientDescription": "SHAREH1",
        #"counterpartReference": "76542",
        #"counterpartDescription": "IFH1",
        #"shareholderReference": "6432",
        #"shareholderDescription": "SHAREH1",
        #"isin": "MA90002",
        #"operationType": "TRANSFER_OUT",
        #"transDirection": 1,
        #"assetType": "EQUITY",
        #"assetDescription": "JHZZT",
        #"assetId": 41,
        #"assetReference": "7777",
        #"quantity": 12,
        #"quantityType": "UNIT",
        #"shareholderId": 11,
        #"counterpartId": 11,
        #"beneficiaryId": 0,
        #"csdId": 0,
        #"csdReference": "",
        #"csdDescription": "",
        #"clientSecurityAccount": "236721419000264320000033333010301",
        #"clientCashAccount": "",
        #"beneficiarySecurityAccount": "",
        #"beneficiaryCashAccount": "",
        #"currencyCashAccount": 0,
        #"nostroSecurityAccount": 0,
        #"nostroCashAccount": 0,
        #"operationDate": "2024-01-28",
        #"valueDate": null,
        #"settlementDate": "2024-01-29",
        #"grossAmount": 1200,
        #"vatAmount": 0,
        #"whtAmount": 0,
        #"netAmount": 1200,
        #"cashAccountcurrencyId": 0,
        #"cashAccountcurrency": "",
        #"currency": "MAD",
        #"accuredInterest": 0,
        #"settlementPlace": "",
        #"reversed": false,
        #"clientProviderId": 0,
        #"clientProviderDescription": "",
        #"sens": "RECEIVE",
        #"maturityDate": null,
        #"status": "PREVALIDATED",
        #"rate": 0,
        #"transferred": true,
        #"price": 100,
        #"active": true,
        #"placeOfSettlement": "MAROCLEAR",
        #"origin": "MANUAL"
      #}
      #"""
    #Then the IRL entity should be saved successfully
    #And the IRLs should be marked as PREVALIDATED
  #
  ###########################################################
  #@Skip
  #Scenario: Validate IRLs
    #When I validate the IRL: 
    #"""
      #{
        #"id": 1,
              #"reference": "A000000000000001",
              #"clientReference": "6432",
              #"clientDescription": "SHAREH1",
              #"counterpartReference": "76542",
              #"counterpartDescription": "IFH1",
              #"shareholderReference": "6432",
              #"shareholderDescription": "SHAREH1",
              #"isin": "MA90002",
              #"operationType": "BUY",
              #"transDirection": 1,
              #"assetType": "EQUITY",
              #"assetDescription": "JHZZT",
              #"assetId": 41,
              #"assetReference": "7777",
              #"quantity": 12,
              #"quantityType": "UNIT",
              #"shareholderId": 11,
              #"counterpartId": 11,
              #"beneficiaryId": 0,
              #"csdId": 0,
              #"csdReference": "",
              #"csdDescription": "",
              #"clientSecurityAccount": "236721419000264320000033333010301",
              #"clientCashAccount": "",
              #"beneficiarySecurityAccount": "",
              #"beneficiaryCashAccount": "",
              #"currencyCashAccount": 0,
              #"nostroSecurityAccount": 0,
              #"nostroCashAccount": 0,
              #"operationDate": "2024-01-28",
              #"valueDate": null,
              #"settlementDate": "2024-01-29",
              #"grossAmount": 1200,
              #"vatAmount": 0,
              #"whtAmount": 0,
              #"netAmount": 1200,
              #"cashAccountcurrencyId": 0,
              #"cashAccountcurrency": "",
              #"currency": "MAD",
              #"accruedInterest": 0,
              #"settlementPlace": "",
              #"reversed": false,
              #"clientProviderId": 0,
              #"clientProviderDescription": "",
              #"sens": "RECEIVE",
              #"createdOn": "2024-01-28T02:14:34.290Z",
              #"maturityDate": null,
              #"status": "PREVALIDATED",
              #"rate": 0,
              #"transferred": true,
              #"price": 100,
              #"active": true,
              #"placeOfSettlement": "MAROCLEAR",
              #"origin": "MANUAL"
      #}
      #"""
    #Then the IRLs should be marked as VALIDATED
#
  ###########################################################
  #@Skip
  #Scenario: Settle IRLs
    #When I settle the IRL:
    #"""
      #{
        #"id": 1,
              #"reference": "A000000000000001",
              #"clientReference": "6432",
              #"clientDescription": "SHAREH1",
              #"counterpartReference": "76542",
              #"counterpartDescription": "IFH1",
              #"shareholderReference": "6432",
              #"shareholderDescription": "SHAREH1",
              #"isin": "MA90002",
              #"operationType": "BUY",
              #"transDirection": 1,
              #"assetType": "EQUITY",
              #"assetDescription": "JHZZT",
              #"assetId": 41,
              #"assetReference": "7777",
              #"quantity": 12,
              #"quantityType": "UNIT",
              #"shareholderId": 11,
              #"counterpartId": 11,
              #"beneficiaryId": 0,
              #"csdId": 0,
              #"csdReference": "",
              #"csdDescription": "",
              #"clientSecurityAccount": "236721419000264320000033333010301",
              #"clientCashAccount": "",
              #"beneficiarySecurityAccount": "",
              #"beneficiaryCashAccount": "",
              #"currencyCashAccount": 0,
              #"nostroSecurityAccount": 0,
              #"nostroCashAccount": 0,
              #"operationDate": "2024-01-28",
              #"valueDate": null,
              #"settlementDate": "2024-01-29",
              #"grossAmount": 1200,
              #"vatAmount": 0,
              #"whtAmount": 0,
              #"netAmount": 1200,
              #"cashAccountcurrencyId": 0,
              #"cashAccountcurrency": "",
              #"currency": "MAD",
              #"accruedInterest": 0,
              #"settlementPlace": "",
              #"reversed": false,
              #"clientProviderId": 0,
              #"clientProviderDescription": "",
              #"sens": "RECEIVE",
              #"createdOn": "2024-01-28T02:14:34.290Z",
              #"maturityDate": null,
              #"status": "VALIDATED",
              #"rate": 0,
              #"transferred": true,
              #"price": 100,
              #"active": true,
              #"placeOfSettlement": "MAROCLEAR",
              #"origin": "MANUAL"
      #}
      #"""
    #Then the IRLs should be marked as SETTLED
#
  ###########################################################
  #@Skip
  #Scenario: Cancel IRLs
    #When I cancel the IRL:
    #"""
      #{
        #"id": 1,
              #"reference": "A000000000000001",
              #"clientReference": "6432",
              #"clientDescription": "SHAREH1",
              #"counterpartReference": "76542",
              #"counterpartDescription": "IFH1",
              #"shareholderReference": "6432",
              #"shareholderDescription": "SHAREH1",
              #"isin": "MA90002",
              #"operationType": "BUY",
              #"transDirection": 1,
              #"assetType": "EQUITY",
              #"assetDescription": "JHZZT",
              #"assetId": 41,
              #"assetReference": "7777",
              #"quantity": 12,
              #"quantityType": "UNIT",
              #"shareholderId": 11,
              #"counterpartId": 11,
              #"beneficiaryId": 0,
              #"csdId": 0,
              #"csdReference": "",
              #"csdDescription": "",
              #"clientSecurityAccount": "236721419000264320000033333010301",
              #"clientCashAccount": "",
              #"beneficiarySecurityAccount": "",
              #"beneficiaryCashAccount": "",
              #"currencyCashAccount": 0,
              #"nostroSecurityAccount": 0,
              #"nostroCashAccount": 0,
              #"operationDate": "2024-01-28",
              #"valueDate": null,
              #"settlementDate": "2024-01-29",
              #"grossAmount": 1200,
              #"vatAmount": 0,
              #"whtAmount": 0,
              #"netAmount": 1200,
              #"cashAccountcurrencyId": 0,
              #"cashAccountcurrency": "",
              #"currency": "MAD",
              #"accruedInterest": 0,
              #"settlementPlace": "",
              #"reversed": false,
              #"clientProviderId": 0,
              #"clientProviderDescription": "",
              #"sens": "RECEIVE",
              #"createdOn": "2024-01-28T02:14:34.290Z",
              #"maturityDate": null,
              #"status": "PREVALIDATED",
              #"rate": 0,
              #"transferred": true,
              #"price": 100,
              #"active": true,
              #"placeOfSettlement": "MAROCLEAR",
              #"origin": "MANUAL"
      #}
      #"""
    #Then the IRLs should be marked as REJECTED
